name: CD

on: [push]

jobs:
  copy_backend_to_server:
    name: Copy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Clear Path
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 stop SyTW-B
            pm2 delete SyTW-B
            rm -rf /root/SyTW-Backend/*

      - name: Copy files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./backend/.
          remote: /root/SyTW-Backend/
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}

  run_backend:
    name: Run Backend
    needs: [copy_backend_to_server]
    runs-on: ubuntu-latest
    steps:
      - name: Run Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/SyTW-Backend
            npm install
            npm run build
            pm2 start node --name SyTW-B -- ./build/index.js